// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbt0JGw1pzLYl0QabLLFOZXYxPduczhY0',
    appId: '1:758441291240:web:5f325c133fe4408dcd085d',
    messagingSenderId: '758441291240',
    projectId: 'amine-managing-page',
    authDomain: 'amine-managing-page.firebaseapp.com',
    storageBucket: 'amine-managing-page.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTAdrPw6hTwzpN_wotQmlz_UWYqMOfj2U',
    appId: '1:758441291240:android:1b69bc1deabc6869cd085d',
    messagingSenderId: '758441291240',
    projectId: 'amine-managing-page',
    storageBucket: 'amine-managing-page.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1X1v0o8oyFKgXh85U_5opwjAQEOEK-1s',
    appId: '1:758441291240:ios:8449668d81cd0425cd085d',
    messagingSenderId: '758441291240',
    projectId: 'amine-managing-page',
    storageBucket: 'amine-managing-page.firebasestorage.app',
    iosBundleId: 'com.example.amineGraph',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1X1v0o8oyFKgXh85U_5opwjAQEOEK-1s',
    appId: '1:758441291240:ios:8449668d81cd0425cd085d',
    messagingSenderId: '758441291240',
    projectId: 'amine-managing-page',
    storageBucket: 'amine-managing-page.firebasestorage.app',
    iosBundleId: 'com.example.amineGraph',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbt0JGw1pzLYl0QabLLFOZXYxPduczhY0',
    appId: '1:758441291240:web:904e1322713b38c3cd085d',
    messagingSenderId: '758441291240',
    projectId: 'amine-managing-page',
    authDomain: 'amine-managing-page.firebaseapp.com',
    storageBucket: 'amine-managing-page.firebasestorage.app',
  );
}
